### PR TITLE
feat(cloud): updating ksActionsManager to use translations

### PR DESCRIPTION
**Pull request by alonso-kleeen**
### Added:

- Adding some translations to the "Add" section of the list of all records component `ksActionsManager`.

### CODE REVIEW

**Comment by jorgekleeen** [comment]
In the future, let's use the Jira id of the branch name. In that way, that make things easier to track down.

**Comment by alonso-kleeen** [comment]
> In the future, let's use the Jira id of the branch name. In that way, that make things easier to track down.

Sure, though I don't think there's a specific Jira ticket for this, is there? @sebaskleeen

**Comment by aaron-kleeen** [comment]
It's not an specific jira ticket for this.

**Comment by alonso-kleeen** [comment]
Since there are some new changes in the generated translation IDs, [per Jorge](https://github.com/KLEEEN-SOFTWARE/kapitan/pull/487#discussion_r382720646) ([commit](https://github.com/KLEEEN-SOFTWARE/kapitan/pull/487/commits/0803febd04a60bd9db7bec209723411dfbbc24c0)), I'm putting this on hold until I use those new keys here.

**Comment by alonso-kleeen** [comment]
Okay, new translations keys are up (`app.modal.action.*` instead of `app.entirety.action.*`.

**Comment by alonso-kleeen** [comment]
On hold until https://github.com/KLEEEN-SOFTWARE/kapitan/pull/487 is merged, since it's a direct dependency.

**Pull request merged**
